# Generated by Django 3.0.3 on 2020-02-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=2083)),
                ('count', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
