# Generated by Django 3.0.3 on 2020-02-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uliya', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetailsForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=200)),
                ('user_phone_number', models.IntegerField(max_length=15)),
                ('user_message', models.CharField(max_length=300)),
            ],
        ),
    ]
